---
name: OptiGrid
slug: optigrid
version: dev
description: "Energy optimization with battery management"
url: "https://github.com/ViniTheVini/ha-addon-optigrid/"
arch:
  - amd64
  - aarch64
startup: services
hassio_api: true
homeassistant_api: true
ports:
  8000/tcp: 8000
options:
  log_level: "info"
schema:
  log_level: "list(critical|error|warning|info|debug|trace)"
